apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edge-proxy-deployment
  labels:
    app: edge-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-proxy
    spec:
      containers:
      - name: edge-proxy
        image: eu.gcr.io/mimir-185212/edge-proxy:0.1-DEV
        ports:
        - containerPort: 8080
          name: svc-port
        livenessProbe:
          httpGet:
            path: /health
            port: svc-port
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: svc-port
          initialDelaySeconds: 20
        imagePullPolicy: Always
      imagePullSecrets:
      - name: gcr-json-key
