apiVersion: v1
kind: Service
metadata:
  name: edge-proxy
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https-port
      port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app: edge-proxy
  type: LoadBalancer
